#!/usr/bin/env bash

ANTIDOTE_REPO=${XDG_PROJECTS_DIR:-$HOME/Projects}/antidote

if [[ ! -d $ANTIDOTE_REPO ]]; then
  echo ":: Installing antidote..."
  git clone --depth=1 https://github.com/mattmc3/antidote $ANTIDOTE_REPO
else
  echo ":: antidote is already installed."
fi
