#!/usr/bin/env bash

NVM_DIR="$HOME/.nvm"

if [[ ! -d $NVM_DIR ]]; then
  echo ":: Installing nvm..."
  wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
else
  echo ":: nvm is already installed."
fi

nvm install --lts
nvm use default
npm i -g pnpm bun deno @nomicfoundation/solidity-language-server
