#!/usr/bin/env bash

TMUX_DIR="$HOME/.tmux"

if [[ ! -d $TMUX_DIR ]]; then
  echo ":: Installing tpm..."
  git clone https://github.com/tmux-plugins/tpm $TMUX_DIR/plugins/tpm
else
  echo ":: tpm is already installed."
fi
